### ISSUE TITLE
v2: desktop ui bundle does not build, inbox.test.ts fixture lacks the new inbox.scroll

### ISSUE THREAD

**Issue by stevengonsalvez** [stevengonsalvez/agents-in-a-box#1292]
On `origin/v2` at dfe1f1e47 (the merge of #1280), `npm run build` in `ainb-tui/crates/ainb-desktop/ui` fails at its `tsc --noEmit --strict` step, so no ui bundle and no desktop bundle can be produced from v2:

```
src/inbox.test.ts(22,81): error TS2322: Type '{ entries: InboxRowFrame_Serialize[]; unread: number; recipient: string; absent: string | null; unreachable: string | null; rows_cut: number; summaries_cut: number; ... }' is not assignable to type 'InboxView_Serialize'.
  Types of property 'scroll' are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
```

Cause: d1527cd03 (#1261, d3p-b) regenerated `ainb-app/bindings/AppState.ts` with a required `scroll: number` on the inbox view, and the `view()` fixture in `src/inbox.test.ts` (#1280, d3p-c, branched before it) builds an `InboxView_Serialize` without it. Each PR was green on its own base; the merge is not.

Fix: add `scroll: 0` to the fixture in `src/inbox.test.ts` (one line). Until then the bundle can be produced with `npx vite build` directly, which skips the type check; the confirmation pass on dfe1f1e47 did that and says so.
